apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-gitops-deployment
  labels:
    app: demo-gitops
spec:
  selector:
    matchLabels:
      app: demo-gitops
  replicas: 2 
  template:
    metadata:
      labels:
        app: demo-gitops
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.25.3 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: demo-gitops 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort 